### ISSUE TITLE
[FIRMWARE REQUEST]: UDM-Pro 2.4.27

### ISSUE THREAD

**Issue by apo-mak** [whi-tw/macvlan-unifios#12]
### Firmware Version

2.4.27

### Kernel Version

4.19.152-ui-alpine

### Any other information / context

https://community.ui.com/releases/97ae6597-ee40-4e72-8e8f-76d067f84d37

release date: 08-Feb-2023

### Is there an additional request for this?

- [X] I have searched the existing issues

**Comment by whi-tw** [comment]
👀 looks like this hasn't been released for the UDR - latest is 3.0.13: https://www.ui.com/download/unifi/unifi-dream-router

Have they now stopped shipping macvlan on UDM as well?

**Comment by apo-mak** [comment]
> 
that is what it is look's like unfortunately 😞 .
From what I understand they plan to move the UDMP to the same version ( and state) as the UDR.
There was talks about a single OS base for their consoles.

**Comment by whi-tw** [comment]
Booo ok. I'll do the GPL request today, so it'll be the end of next week earliest.

**Comment by whi-tw** [comment]
GPL request requested:

```
Hi Open Source Requests team!

Can you please provide me with the following GPL dumps:

1:
  Device: UDM
  Firmware: 2.4.27
2:
  Device: UDM-Pro
  Firmware: 2.4.27
3:
  Device: UDM-SE
  Firmware: 3.0.13

Many thanks,

Tom Whitwell
```

**Comment by apo-mak** [comment]
firstly thank you very much.
And this at the end can be a good thing if they manage to have one OS Base for all the consoles,
we will only need one macvlan base variant.

**Comment by whi-tw** [comment]
No trouble!

It is possible, although they may use different architectures / kernel options etc. between models, so It'll probably have to still be built on a per-device basis. We'll see!

I've reworked the repository to allow for multiple devices - just need Ubiquiti to get back to me with the GPL dumps.

Can you possibly run `uname -m` on your UDMP for me, and give me the output?

**Comment by ZeroClover** [comment]
> Can you possibly run `uname -m` on your UDMP for me, and give me the output?

```
root@Zero-UDM-Pro:~# uname -m
aarch64
```

**Comment by apo-mak** [comment]
> > Can you possibly run `uname -m` on your UDMP for me, and give me the output?
> 
> ```
> root@Zero-UDM-Pro:~# uname -m
> aarch64
> ```

root@UDMPRO:~# uname -m
aarch64

**Comment by whi-tw** [comment]
Note: UDM-SE still has macvlan enabled, so out of scope for this

**Comment by apo-mak** [comment]
> Amazing, thanks all. I don't have a UDMP to test on, so just need to make sure I build it right once the GPL dumps arrive.

ping me when you need to test it :)

**Comment by whi-tw** [comment]
Update: I've received the GPL archives - gonna get a branch up soon

**Comment by apo-mak** [comment]
> Update: I've received the GPL archives - gonna get a branch up soon

can I help with the testing ?

**Comment by whi-tw** [comment]
sorry, i am on it. building isn't quite as simple as in other firmware versions i've built.

**Comment by whi-tw** [comment]
i can't get this to build for UDMP. I'm not really experienced enough to debug it either. happy for others to take a look and let me know what could be happening - build outputs should be visible on #22

**Comment by whi-tw** [comment]
I've pushed out the release for UDM. UDMP is still stuck. I've added a new branch / PR for UDMP: #24
